resume_directory: ../data/input/example_resumes
summary_output_directory: ../data/output
data_schema_dir: ../data/schema

extractors:
 experience:
  - Data scientist
  - SDE
  - developer
  - software developer
  - software engineer
  - Data Analyst
  - Business
  - Web
  - Front-end
  - Front end
  - Full stack
  - full-stack
  - security
  - network
  - application
  - mobile
  - IOS
  - Android

 platforms:
  - Linux
  - Windows
  - Mac
  - IOS
  - Android


 database:
  - SQL
  - MySQL
  - Postgress
  - Postgresql
  - Oracle
  - MS SQL Server
  - SQLite
  - Redis
  - Access
  - MongoDB
  - DB2
  - Cassandra
  - PostgreSQL
  - Elasticsearch
  - Teradata
  - SAP Adaptive server
  - Solr
  - Splunk
  - HBase
  - Hive
  - SAP HANA
  - CouchDB
  - Azure
  - MS Azure SQL Database
  - Informix
  - Couchbase
  - Filemaker
  - Neo4j
  - DynamoDB
  - Amazon DynamoBD
  - Memcached

 programming:
  - Java
  - C
  - C\+\+
  - C#
  - Python
  - Visual Basic .NET
  - PHP
  - JavaScript
  - Delphi
  - Object Pascal
  - Swift
  - Perl
  - Ruby
  - Assembly language
  - R
  - Visual Basic
  - Objective-C
  - Go
  - MATLAB
  - PL
  - SQL
  - Scratch
  - SAS
  - D
  - Dart
  - ABAP
  - COBOL
  - Ada
  - Fortran
  - Transact-SQL
  - Lua
  - Scala
  - Logo
  - F#
  - Lisp
  - LabVIEW
  - Prolog
  - Haskell
  - Scheme
  - Groovy
  - RPG
  - Apex
  - Erlang
  - MQL4
  - Rust
  - Bash
  - Ladder Logic
  - Q
  - Julia
  - Alice
  - VHDL
  - Awk


 machinelearning:
  - sklearn
  - scikit-learn
  - sk-learn
  - tensorflow
  - tf
  - tensor-flow
  - keras
  - h20

 open-source:
  - github
  - bitbucket
  - gitlab
  - sourceforge
  - gitkraken
