resume_directory: ../data/input/example_resumes
summary_output_directory: ../data/output
data_schema_dir: ../data/schema

extractors:
 experience:
  - Data scientist
  - SDE
  - developer
  - software developer
  - software engineer
  - Data Analyst
  - Business
  - Web
  - Front-end
  - Front end
  - Full stack
  - full-stack
  - security
  - network
  - application
  - mobile
  - IOS
  - Android

 platforms:
  - Linux
  - Windows
  - Mac
  - IOS
  - Android

 database:
  - SQL
  - MySQL
  - Postgress
  - Postgresql
  - Oracle
  - MS SQL Server
  - SQLite
  - Redis
  - Access
  - MongoDB
  - DB2
  - Cassandra
  - PostgreSQL
  - Elasticsearch
  - Teradata
  - SAP Adaptive server
  - Solr
  - Splunk
  - HBase
  - Hive
  - SAP HANA
  - CouchDB
  - Azure
  - MS Azure SQL Database
  - Informix
  - Couchbase
  - Filemaker
  - Neo4j
  - DynamoDB
  - Amazon DynamoBD
  - Memcached

 programming:
  - Java
  - C
  - C\+\+
  - C#
  - Python
  - Visual Basic .NET
  - PHP
  - JavaScript
  - Delphi
  - Object Pascal
  - Swift
  - Perl
  - Ruby
  - Html
  - CSS
  - Assembly language
  - R
  - Visual Basic
  - Objective-C
  - Go
  - MATLAB
  - PL
  - SQL
  - Scratch
  - SAS
  - D
  - Dart
  - ABAP
  - COBOL
  - Ada
  - Fortran
  - Transact-SQL
  - Lua
  - Scala
  - Logo
  - F#
  - Lisp
  - LabVIEW
  - Prolog
  - Haskell
  - Scheme
  - Groovy
  - RPG
  - Apex
  - Erlang
  - MQL4
  - Rust
  - Bash
  - Ladder Logic
  - Q
  - Julia
  - Alice
  - VHDL
  - Awk

 machinelearning:
  - sklearn
  - scikit-learn
  - sk-learn
  - tensorflow
  - keras
  - classification
  - supervised
  - unsupervised
  - cluster
  - SVM
  - regression
  - ensemble
  - Adaboost
  - CNN
  - RNN
  - Bayes

 open-source:
  - git
  - github
  - bitbucket
  - gitlab
  - sourceforge
  - gitkraken
  - arx
  - bazaar
  - bitkeeper
  - codeville
  - darcs
  - dcvs
  - fossil
  - mercurial
  - monotone
  - svk
  - veracity

 code-review:
  - Collaborator
  - Review Assistant
  - Codebrag
  - Gerrit
  - Codestriker
  - Rhodecode
  - Phabricator
  - Crucible
  - Veracode
  - Review Assistant
  - Review Board

 distributed-system:
  - hadoop
  - spark
  - kafka
  - pig
  - zookeeper
  - hbase
  - flume
  - impala
  - sqoop
  - OOZIE
  - Sentry
  - hdfs
  - mapreduce
  - YARN
  - Flink
  - Solr

 cloud-platforms:
  - AWS
  - cloud
  - Azure
  - dropbox
  - box

 virtulization-technology:
  - vmware
  - virtualbox
  - hypervisor
  - citrix
  - hyper-v
  - emulation
  - bochs
  - qemu
  - kvm
  - zones
  - openVZ
  - Docker

 frontend-frameworks:
  - Angular.JS
  - React.JS
  - Meteor.JS
  - Vue.JS
  - Backbone.JS
  - jade
  - UNDERSCORE.JS
  - Boootstrap
  - jQuery
  - gulp
  - grunt
  - motion.js
  - flux
  - Knockout
  - Ember.js

 backend-frameworks:
  - Django
  - Spring
  - Rails
  - Symfony
  - JSF
  -


 others:
  - Unity
  - unity3d
  - XML
  - JSON




